# Base image for raspbian_docker_base
# docker build --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy -t raspbian_docker_base:latest .
# docker container run -it -d raspbian_docker_base:latest bash
# docker container exec -it <container-id> bash
FROM balenalib/raspberrypi3
RUN sudo apt-get update
